model_name: Us
model_key: us
model_version: v0.9.1_w_cutoff # 2024-07-11
matbench_discovery_version: 1.1.2 # required
date_added: "2024-07-13" # required
date_published: "2024-02-06"
authors: # required (only name, other keys are optional)
  - name: Yutack Park
    affiliation: Seoul National University
    email: parkyutack@snu.ac.kr
    orcid: https://orcid.org/0009-0008-8690-935X
  - name: Jaesun Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-6646-1318
  - name: Seungwoo Hwang
    affiliation: Seoul National University
    orcid: https://orcid.org/0000-0002-1523-8340
  - name: Seungwu Han
    affiliation: Seoul National University, Korea Institute for Advanced Study
    email: hansw@snu.ac.kr
    orcid: https://orcid.org/0000-0003-3958-0922
    corresponding: true
trained_by:
  - name: Saerom Choi
    affiliation: Samsung Advanced Institute of Technology, Seoul National University
    orcid: https://orcid.org/0009-0004-2240-5428
repo: https://github.com/MDIL-SNU/SevenNet # required
url: https://github.com/MDIL-SNU/SevenNet/tree/afb56e10b6/sevenn/pretrained_potentials/SevenNet_0__11July2024
doi: https://doi.org/10.1021/acs.jctc.4c00190
paper: https://arxiv.org/abs/2402.03789
pypi: https://pypi.org/project/sevenn

openness: OSOD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 842_440
n_estimators: 1

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: Huber - delta=0.01
  loss_weights:
    energy: 1.0
    force: 1.0
    stress: 0.01
  batch_size: 4096 # 32 (gpus) * 128 (batch per gpu) = 4096 (total batch size)
  initial_learning_rate: 0.010
  learning_rate_schedule: LinearLR - start_factor=1.0, total_iters=600, end_factor=0.0001
  epochs: 600
  n_layers: 5
  n_features: 128 l=0 scalars, 64 l=1 vectors, 32 l=2 tensors
  n_radial_bessel_basis: 8
  radial_cutoff: 5.0 # Å
  sph_harmonics_l_max: 2

requirements:
  torch: 2.2.1
  torch-geometric: 2.5.2
  torch_scatter: 2.1.2
  ase: 3.22.1
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [MPtrj]

notes:
  Description: |
    SevenNet is a graph neural network interatomic potential package that supports parallel molecular dynamics simulations.
    In the SevenNet-0 model, based on the NequIP architecture, the tensor product in the self-connection layer, which includes numerous element-specific parameters, is replaced by a linear (or self-interaction) layer, this reduces the number of parameters from 16_240_000 (c.f. GNoME) to 842_440.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 1.310
      pred_file: models/us/sevennet_results/kappa_0_1.json.gz
  geo_opt:
    pred_file: models/us/results-finetuned/finetune-half-lr-3.json.gz
    pred_col: sevennet_structure
    rmsd: 0.4193
    symmetry_decrease: 0.3557
    symmetry_match: 0.4535
    symmetry_increase: 0.1446
    n_structs: 256963.0
  discovery:
    pred_file: models/us/results-finetuned/half-lr-002_800.csv.gz
    pred_col: e_form_per_atom_alphanet
    full_test_set:
      F1: 0.843 # fraction
      DAF: 5.216 # dimensionless
      Precision: 0.895 # fraction
      Recall: 0.797 # fraction
      Accuracy: 0.949 # fraction
      TPR: 0.797 # fraction
      FPR: 0.019 # fraction
      TNR: 0.981 # fraction
      FNR: 0.203 # fraction
      TP: 35135.0 # count
      FP: 4122.0 # count
      TN: 208749.0 # count
      FN: 8957.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.043 # eV/atom
      R2: 0.943 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.994 # fraction
      DAF: 6.469 # dimensionless
      Precision: 0.989 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.989 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9890.0 # count
      FP: 110.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.017 # eV/atom
      RMSE: 0.044 # eV/atom
      R2: 0.954 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.863 # fraction
      DAF: 5.979 # dimensionless
      Precision: 0.914 # fraction
      Recall: 0.818 # fraction
      Accuracy: 0.96 # fraction
      TPR: 0.818 # fraction
      FPR: 0.014 # fraction
      TNR: 0.986 # fraction
      FNR: 0.182 # fraction
      TP: 27300.0 # count
      FP: 2566.0 # count
      TN: 179548.0 # count
      FN: 6074.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.042 # eV/atom
      R2: 0.949 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
